create table users (
    id int8 generated by default as identity,
    username varchar(255) not null,
    password varchar(255) not null,
    photo varchar(255),
    role varchar(255) not null,
    active boolean not null,
    primary key (id)
);

insert into users values(1, 'admin', 'admin4ik', 'images/user/admin_default.png', 'ADMIN', true);
insert into users values(2, 'useruser', 'password', 'images/user/usr_default.png', 'USER', true);